#%RAML 1.0 Library
usage: This is common Library for MICORP Project

traits:
  errorResponses: !include traits/errorResponses.raml

resourceTypes:
  commonResourceType : !include resourceTypes/commonResourceTypes.raml